### ISSUE TITLE
non-stdlib dependencies: downgrade from pydantic or upgrade from flit?

### ISSUE THREAD

**Issue by SomeoneSerge** [ConnorBaker/cuda-redist-find-features#1]

**Comment by ConnorBaker** [comment]
I think I remember we came to a consensus on non-stdlib dependencies being okay -- if I'm misremembering, please re-open!

**Comment by SomeoneSerge** [comment]
If you switch over to something like poetry, you could list the dependencies in `pyproject.toml` and they'll be checked during the wheel install phase by the nixpkgs' `buildPythonPackage`

**Comment by ConnorBaker** [comment]
Would that be through `pythonImportsCheck` (which I just added[^1]) or some other mechanism?

I had tried poetry but wasn't too happy with it (both inside and outside of Nix) and moved to mostly Nix for managing my python stuff now. I chose flit over setup tools because it seems to be gaining support/adoption from a number of large projects in the ecosystem. (More concrete details escape me at the moment.)

[^1]: https://github.com/ConnorBaker/cuda-redist-find-features/blob/28255c03d9b0f197491568acef3705dece51ae74/nix/packages/cuda-redist-find-features.nix#L29-L32)

**Comment by SomeoneSerge** [comment]
> Would that be through pythonImportsCheck (which I just added[1](https://github.com/ConnorBaker/cuda-redist-find-features/issues/1#user-content-fn-1-8504e0d7f26d1bf5fdfaf8e6c1edc633)) or some other mechanism?

Poetry and setuptools include information about dependencies in the wheel, so when buildPythonPackage does something like `pip install *.whl` it happens automatically

Otherwise I absolutely agree with the sentiment. Maybe a pyproject.toml with the setuptools backend then

**Comment by SomeoneSerge** [comment]
EDIT: Oh! Turns out flit nowadays [supports dependencies](https://flit.pypa.io/en/stable/pyproject_toml.html#pyproject-project-dependencies) as well and you already specify them! My bad, I didn't check their docs
